version: 2
publish: &publish
  working_directory: ~/my-app
  docker:
    - image: circleci/node:16
  steps:
    - checkout

    - run:
        name: Installing dependencies
        command: npm ci

    - run:
        name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: NFQOtLrRHC0YBpDQMjaUU_WYLKmfvw7-doGHPEcC

    - run:
        name: Publish to Expo
        command: npx expo-cli publish --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL

jobs:
  publish_to_expo_dev:
    environment:
      EXPO_RELEASE_CHANNEL: dev
    <<: *publish

  publish_to_expo_prod:
    environment:
      EXPO_RELEASE_CHANNEL: default
    <<: *publish

workflows:
  version: 2
  my_app:
    jobs:
      - publish_to_expo_dev:
          filters:
            branches:
              only: development
      - publish_to_expo_prod:
          filters:
            branches:
              only: main
